blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts

  # get 'posts/index'

  # get 'posts/show' => 'posts#show'

  # get 'posts/new'

  # get 'posts/create'

  # delete 'posts/delete' => 'posts#destroy'

  # get 'posts/update'

  # get '/posts/edit' => 'posts#edit'

  get '/posts/:id' => 'posts#show'

  post '/posts/create' => 'posts#create'

  get '/showall' => 'posts#show_all'

  get '/mypost' => 'posts#mypost'

  resources :users, except: [:show]
  #get 'users/create'
  #resources :posts, expect: [:show]
  #get 'users/index'

  #get 'users/create'

  #get 'users/new'

  #get 'users/update'

  #get 'users/edit'

  get '/isauthenticated' => 'users#get_login'

  get '/userdetails/:id' => 'users#user_details'

  put '/edituser' => 'users#update'

  delete '/deleteusers' => 'users#destroy'

  get 'login' => 'users#login'

  post 'login' => 'users#verify'

  get 'logout' => 'users#logout'

  get '*path'=>'users#main'

  root :to => "users#main"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates_presence_of :post
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_cache_headers
  before_action :create_user
  # def index
  #   @user=User.new
  #   uid=session[:user_id]
  #   #p "UID #{uid}"
  #   if uid.blank?
  #     redirect_to login_path
  #   else
  #     @user=User.find(uid)
  #   end
  # end

  def show_all
    if session[:user_id].present?
      @posts = Post.all
      render json: {
          #session: session,
          posts: @posts.to_json
        },status: 200
    # else
    #   render json: {
    #       #session: session,
    #       message: "Session not found"
    #     },status: 404
    end
  end

  def mypost
    #begin
      #@post = Post.where(user_id: @user.id)
      
      @post=@user.posts
      render json: {
        #session: session,
        posts: @post.to_json
      },status: 200
    #rescue
      # render json: {
      #   #session: session,
      #   posts: @post.to_json
      # },status: 404
    #end
  end
  def show
    begin
      @post = Post.find(params[:id])
      @usersh = User.find(@post.user_id)
      render json: {
        post: @post.to_json,
        user: @usersh.to_json
      },status: 200
    rescue
      render json: {
        
      },status: 404
    end
  end

  # def new
  #   @post = Post.new
  #   #create_user
  # end
  
  def create
    if @check
      begin
        @post = @user.posts.create(post: params[:post])
        if @post.save!
          render json: {
          id: @post.id.to_json
        },status: 200
        # else
        #   render json: {
        #   status: 422
        # },status: 422
        end
      rescue => exception
        render json: {
          status: 422
        },status: 422
      end
      
    end
  end

  def destroy
    begin
      @post = Post.find_by(id: params[:id])
    if @post.delete && @check
      render json: {
        #session: session,
        
      },status: 200
    # else
    #   p "Inside else"
    #    render json: {
    #     #session: session,
        
    #   },status: 422
    end
    rescue => exception
      render json: {
        message: exception,
        
      },status: 422
    end
    
  end

  # def edit
  #   @post = Post.find(params[:id])
  #   if @post.user_id!=@user.id
  #     redirect_to showall_path
  #   end
  #   #@post.update(name: params[:post][:name], description: params[:post][:comment])
  #   #redirect_to '/posts'
  # end

  def update
    begin
      @post = Post.find(params[:id])
      if @post.user_id==@user.id
        @post.update!(post: params[:post])
        render json: {
          #session: session,
          
        },status: 200
      end
    rescue => exception
      render json: {
        #session: session,
        
      },status: 422
    end
    
  end

  private

  # def post_params
  #   params.require(:post).permit(:post)
  # end

  def create_user
    uid=session[:user_id]
    @check = false;
    if uid.present?
      @user = User.find(uid)
      @check = true;
    else
      render json: {
          status: 422
        },status: 422
    end
  end

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

blog/app/views/posts/destroyedit.html.erb
<h1>Posts#destroyedit</h1>
<p>Find me in app/views/posts/destroyedit.html.erb</p>

blog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<% if @post.present? %>
<hr>
        <%= simple_form_for @post do |f| %>
        <%= f.input :post %>
        <%= f.submit "Update" %>
    <%end%>
<%end%>

blog/app/views/posts/index.html.erb
<h1>User View after login</h1>
<hr>

<% if @user.present? %>
    <%= @user.id %> <%= @user.name %>
    <hr>
    <%= link_to "Create Post", new_post_path %>
    <hr>
    <%= link_to "Show All Post", showall_path %>
    <%= link_to "Show My Post", mypost_path %>
    <%= link_to "Edit User", edit_user_path(@user) %>
    <%= link_to "Delete User", user_path(@user),method: :delete, data:{confirm: 'Are you sure?'} %>
    <%= link_to "Logout", logout_path %>
    <hr>
<% else %>
    <h2>You are logged out, Please Login again!!</h2>
<%end%>

blog/app/views/posts/mypost.html.erb
<% if @post.present? %>
<h1>Display Post's Information</h1>
<hr>
    <%for p in @post %>
    <hr>
       <label for="Post_Id">Post Id:-</label> <%= p.id %><br/>
        <label for="Post">Post:-</label> <%= p.post %><br/>
        <label for="Creation_Time">Creation Time:-</label> <%= p.created_at %><br/>
        <label for="user">User Name:-</label> <%= @user.name %><br/>
        <hr>
        <%= link_to "Edit", edit_post_path(p) %>
        <%= link_to "Delete", post_path(p),method: :delete, data:{confirm: 'Are you sure?'} %>
        <%= link_to "Show All Post", showall_path %>
        <%= link_to "Logout", logout_path %>
    <%end%>
<% else %>
    <h2>No Posts are there!!</h2>
<% end %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>
<hr>
    <%= simple_form_for @post, url: '/posts/create', method: :post do |f| %>
  <%= f.input :post %><br/>
  <%= f.submit 'Save'  %>
  <hr>
  <%= link_to "Show All Post", showall_path %>
  <%= link_to "Show My Post", mypost_path %>
  <%= link_to "Logout", logout_path %>
<% end %>

blog/app/views/posts/show.html.erb
<% if @post.present? %>
<h1>Display Post's Information</h1>
<hr>
       <label for="Post_Id">Post Id:-</label> <%= @post.id %><br/>
        <label for="Post">Post:-</label> <%= @post.post %><br/>
        <label for="Creation_Time">Creation Time:-</label> <%= @post.created_at %><br/>
        <label for="user">User Name:-</label> <%= @usersh.name %><br/>
        <hr>
        <% if @post.user_id==@user.id%>
            <%= link_to "Edit", edit_post_path(@post) %>
            <%= link_to "Delete", post_path(@post),method: :delete, data:{confirm: 'Are you sure?'} %>
        <%end%>
        <%= link_to "Show All Post", showall_path %>
        <%= link_to "Show My Post", mypost_path %>
        <%= link_to "Logout", logout_path %>
<% else %>
    <h2>No Posts are there!!</h2>
<% end %>

blog/app/views/posts/show_all.html.erb
<h1>All Post Page</h1>
<hr>
    <% for p in @posts %>
    <hr>
        <% ps = p.post %>
        <%= link_to "#{ps}", post_path(p) %><br/>
        <% if p.user_id==@user.id%>
            <%= link_to "Edit", edit_post_path(p) %>
            <%= link_to "Delete", post_path(p),method: :delete, data:{confirm: 'Are you sure?'} %>
        <%end%>
        <hr>
<% end %>
<hr>
<%= link_to "New Post", new_post_path %>
<%= link_to "Show My Post", mypost_path %>
<%= link_to "Logout", logout_path %>
<hr>

blog/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>