blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts

  # get 'posts/index'

  # get 'posts/show' => 'posts#show'

  # get 'posts/new'

  # get 'posts/create'

  # delete 'posts/delete' => 'posts#destroy'

  # get 'posts/update'

  # get '/posts/edit' => 'posts#edit'

  get '/posts/:id' => 'posts#show'

  post '/posts/create' => 'posts#create'

  get '/showall' => 'posts#show_all'

  get '/mypost' => 'posts#mypost'

  resources :users, except: [:show]
  #get 'users/create'
  #resources :posts, expect: [:show]
  #get 'users/index'

  #get 'users/create'

  #get 'users/new'

  #get 'users/update'

  #get 'users/edit'

  get '/isauthenticated' => 'users#get_login'

  get '/userdetails/:id' => 'users#user_details'

  put '/edituser' => 'users#update'

  delete '/deleteusers' => 'users#destroy'

  get 'login' => 'users#login'

  post 'login' => 'users#verify'

  get 'logout' => 'users#logout'

  get '*path'=>'users#main'

  root :to => "users#main"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/user.rb
class User < ApplicationRecord
    
    has_many :posts, dependent: :delete_all
    has_secure_password

    #EMAIL_REGEXP=/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/i
    validates_presence_of :email
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates_uniqueness_of :email
    validates_presence_of :mobile_no
    validates_uniqueness_of :mobile_no
    validates_format_of :mobile_no, with: /[0-9]{10}/
    validates_presence_of :password_digest
    PASSWORD_FORMAT = /\A
        (?=.{8,})          # Must contain 8 or more characters
        (?=.*\d)           # Must contain a digit
        (?=.*[a-z])        # Must contain a lower case character
        (?=.*[A-Z])        # Must contain an upper case character
        (?=.*[[:^alnum:]]) # Must contain a symbol
    /x

    

    validates :password, 
        presence: true, 
        length: { :within => 6..40 }, 
        format: { with: PASSWORD_FORMAT }, 
        confirmation: true, 
        on: :create

    validates :password, 
        allow_nil: false, 
        length: { :within => 6..40 }, 
        format: { with: PASSWORD_FORMAT }, 
        confirmation: true, 
        on: :update

    private

    # def is_number? string
    #     true if Integer(string) rescue false
    #   end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_cache_headers
  
  @@isAuthenticated=0
  

  # def index
    
  # end

  def user_details
    begin
      @user=User.find(params[:id]);
      if @user.present?
      render json: {
            user:@user.to_json
          },status: 200
      # else
      #   render json: {
      #       user:"User not found"
      #     },status: 404
      end
      rescue => exception
        render json: {
            user:"User not found"
          },status: 404
    end
    
  end

  def get_login
   # p "isAuthenticated #{@@isAuthenticated}"
   begin
     if session[:user_id].present?
      @user=User.find(session[:user_id])
      @@isAuthenticated=@user.id
      #p "User Inside get_login #{@user}"
      render json: {
          isauthenticated: @@isAuthenticated.to_json,
          user:@user.to_json
        },status: 200
    else
      render json: {
          isauthenticated: @@isAuthenticated.to_json
         },status: 404
      end
    rescue => exception
     render json: {
            isauthenticated: @@isAuthenticated.to_json
          },status: 404
    end
    
  end
  def main
    render "main"
  end

  def create
    begin 
      @user = User.new(user_params)
      if @user.save!
        render json: {
          status: 200
        },status: 200
      # else
      #   render json: {
        
      #     },status: 422
      end
    rescue => e 
      #puts "======================="
      render json: {
        error: e.message
        },status: 422
      #puts e.message
    end
  end

  # def new
  #   @user = User.new
  # end

  # def edit
  #   uid=session[:user_id]
  #   if uid.present?
  #     @user = User.find(uid)
  #   else
  #     render json: {
        
  #     },status: 404
  #   end
  # end

  def update
    uid=session[:user_id]
    if uid.present?
      begin
        @user = User.find(uid)
        @user.update!(user_params)
        render json: {},status: 200
      rescue
        render json: {
        
        },status: 422

      end
    # else
    #   render json: {
        
    #   },status: 422
    end
  end

  def destroy
    uid=session[:user_id]
    if uid.present?
      @user = User.find(uid) 
      if @user.destroy
        #session[:user_id] = nil
        reset_session
        @@isAuthenticated = 0
        render json: {
          
        },status: 200
      end
    else
      render json: {
        
      },status: 404
    end
  end

  # def login
  #   if session[:user_id].present?
  #     redirect_to posts_path
  #   else
  #     @user=User.new
  #   end
  # end

  def verify
    #p "Inside Verify"

    @user=User
    .find_by(email: params[:email])
    .try(:authenticate, params[:password]) 
    #p "User is #{@user}"
    if @user.present?
      #p "User is present"
      session[:user_id] = @user.id
      @@isAuthenticated=@user.id
      render json: {
        session: session,
        user: @user.to_json
      },status: 200
    else
      #p "Inside else block"
      render json: {
        #status: 401
      },status: 401
    end
  end

  def logout
    reset_session
    @@isAuthenticated = 0
    render json: {
      status: 200
    },status: 200
  end

  private

  def user_params
    params.permit(:name, :email, :mobile_no, :password)
  end

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/users/create.html.erb
<% if @user.present? %>
<h1>User Creation Successfull</h1>
<hr>
        <%= @user.name %><br/>
        <%= @user.email %><br/>
        <%= @user.mobile_no %><br/>
        
        <%= link_to "Home", users_path %>
<% else %>
    <h2>User Creation Unsuccessfull</h2>
<% end %>

blog/app/views/users/delete.html.erb
<h1>User Deletion Successfull</h1>
<hr>
        <%= link_to "Home", users_path %>

blog/app/views/users/edit.html.erb
<h1>User edit Page</h1>
<hr>
<h1>Edit User</h1>
<% if @user.present? %>
<hr>
        <%= simple_form_for @user do |f| %>
        <%= f.input :name, label_html: { class: 'my_class' } %><br/>
        <%= f.input :email, placeholder: 'user@domain.com' %><br/>
        <%= f.input :mobile_no, input_html: { maxlength: 10 } %><br/>
        <%= f.input :password, hint: false, error_html: { id: 'password_error'} %><br/>
        <%= f.input :password_confirmation %>
        <%= f.button :submit %>
        <% end %>
<hr>
<%= link_to "Logout", logout_path %>
<%end%>

blog/app/views/users/index.html.erb
<h1>Home Page</h1>
<hr>
 <%= link_to "SignIn", login_path, method: :get %>
 <%= link_to "SignUp", new_user_path %>

blog/app/views/users/login.html.erb
<h1>User login Page</h1>
<hr>
   
<%= simple_form_for @user, url: '/login', method: :post  do |f| %>
  <%= f.input :email, placeholder: 'user@domain.com' %><br/>
  <%= f.input :password, hint: false, error_html: { id: 'password_error'} %><br/>
  <%= f.submit 'SignIn' %>
<% end %>

blog/app/views/users/main.html.erb
<%= react_component("Main") %>

blog/app/views/users/new.html.erb
<h1>New Login Page</h1>
<hr>
   
<%= simple_form_for @user, url: '/users', method: :post  do |f| %>
  <%= f.input :name, label_html: { class: 'my_class' } %><br/>
  <%= f.input :email, placeholder: 'user@domain.com' %><br/>
  <%= f.input :mobile_no, input_html: { maxlength: 10 } %><br/>
  <%= f.input :password, hint: false, error_html: { id: 'password_error'} %><br/>
  <%= f.input :password_confirmation %>
  <%= f.submit 'Create User' %>
  <p>
   <b>Password----<br/> 
   * Must contain 8 or more characters<br/>
    * Must contain a digit<br/>
    * Must contain a lower case character<br/>
    * Must contain an upper case character<br/>
    * Must contain a symbol</b>
  </p>
<% end %>

blog/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>